#! /bin/bash

export HOST_IP=${HOST_IP:-$(l5s self -i | jq .)}
# export JOIN_IPS=${JOIN_IPS:-$(l5s nodes -k locutus:role -v master -x)}
export MASTER_IPS=${MASTER_IPS:-$(l5s nodes -k locutus:role -v master)}
export IS_MASTER=$(echo $MASTER_IPS | jq . | jq "contains([\"$HOST_IP\"])")

if [ -z "$IS_MASTER" ]; then
    echo 'Unable to determine server role; aborting.'
    exit 1
fi

if [ ! -f '/etc/nomad/nomad-base.hcl' ]; then
    if [ "$IS_MASTER" == 'true' ]; then
        envsubst < /etc/nomad/nomad-server.hcl > /etc/nomad/nomad-server.hcl
        rm /etc/nomad/nomad-client.hcl
    else
        envsubst < /etc/nomad/nomad-client.hcl > /etc/nomad/nomad-client.hcl
        rm /etc/nomad/nomad-server.hcl
    fi
fi

envsubst < /etc/nomad/nomad-base.tpl > /etc/nomad/nomad-base.hcl
rm /etc/nomad/nomad-base.tpl
