# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'

base_image = "ubuntu/xenial64"
bootstrap_script = "../../provision.sh"
cluster = {
    "l5s-master-1" => { :ip => "172.31.0.2", :role => "master" },
    # "l5s-master-2" => { :ip => "172.31.0.3", :role => "master" },
    # "l5s-master-3" => { :ip => "172.31.0.4", :role => "master" },
    "l5s-minion-1" => { :ip => "172.31.0.5", :role => "minion" },
    # "l5s-minion-2" => { :ip => "172.31.0.6", :role => "minion" }
}
master_ips = cluster.
    select { | k, v | v[:role] == 'master' }.
    map { | k, v | v[:ip] }.
    to_json

Vagrant.configure("2") do | config |
    cluster.each_with_index do | (name, data), i |
        config.vm.define name do | node |
            node.vm.box = base_image
            node.vm.hostname = name
            node.vm.network "private_network", ip: data[:ip]
            node.vm.provision :shell,
                path: bootstrap_script,
                env: {
                    "HOST_IP" => data[:ip],
                    "JOIN_IPS" => master_ips,
                    "MASTER_IPS" => master_ips
                }
        end
    end
end
