#! /bin/bash

# usage:
#     source ./export-credentials <name of aws credential profile>

function get-id () {
    local profile=${*:-'default'}
    cat ~/.aws/credentials | grep $profile -A2 | grep id | cut -d ' ' -f 3
}

function get-secret () {
    local profile=${*:-'default'}
    cat ~/.aws/credentials | grep $profile -A2 | grep secret | cut -d ' ' -f 3
}

if [ "$1" == '' ]; then
    echo 'Using default credential profile'
fi

export AWS_ACCESS_KEY_ID=$(get-id $1)
export AWS_SECRET_ACCESS_KEY=$(get-secret $1)
